// RootLayout.tsx (or RootLayout.js)

import './globals.css'; // Import your global CSS file

import type { Metadata } from 'next';
import PageLayout from './components/PageLayout';

export const metadata: Metadata = {
  title: 'Auth Login For One Data',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
      </head>
      <body className='font-roboto'>
        <PageLayout>{children}</PageLayout>
      </body>
    </html>
  );
}
