import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import PageLayout from './components/PageLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Auth Login For One Data',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageLayout>{children}</PageLayout>
        </body>
    </html>
  )
}
